%---------------------------------------------------------------------------------------------------
% For Paper
% "Nonlinear Distributed Model Predictive Flocking with Obstacle Avoidance"
% by P. Hastedt and H. Werner
% Copyright (c) Institute of Control Systems, Hamburg University of Technology. All rights reserved.
% Licensed under the GPLv3. See LICENSE in the project root for license information.
% Author(s): Philipp Hastedt
%---------------------------------------------------------------------------------------------------

function [Lf2_h,LgLf_h] = feedbackLinearization(in1,m,I_zz,d)
%FEEDBACKLINEARIZATION
%    [LF2_H,LGLF_H] = FEEDBACKLINEARIZATION(IN1,M,I_ZZ,D)

%    This function was generated by the Symbolic Math Toolbox version 8.7.

dpsi = in1(5,:);
psi = in1(3,:);
v = in1(4,:);
t2 = cos(psi);
t3 = sin(psi);
Lf2_h = [-dpsi.*(t3.*v+d.*dpsi.*t2);dpsi.*(t2.*v-d.*dpsi.*t3)];
if nargout > 1
    t4 = 1.0./I_zz;
    t5 = 1.0./m;
    LgLf_h = reshape([t2.*t5,t3.*t5,-d.*t3.*t4,d.*t2.*t4],[2,2]);
end
